spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent_output = true

# This configures Spring Boot to trust and use forwarded headers (like X-Forwarded-For) when behind a proxy or load balancer
server.forward-headers-strategy=framework 

server.port=8080
ADYEN_API_KEY=AQFDhmfxJ4/LbhBHw0m/n3Q5qf3VaY9UCJ16aExb1nSuk2NFisZiGclvMiVgB/7xzYuhmDgJH1GsgudQETXfW49Jvf/ZHBDBXVsNvuR83LVYjEgiTGAH-pvhJysf+VkKyy76UoTR31VSTntUgniiwhETmUJWRjW0=-i1iF:d6%pB(xq{U*s(f
ADYEN_CLIENT_KEY=test_HNY6C6IYO5EIBOPFRUYJFORINYZZM656
ADYEN_MERCHANT_ACCOUNT=AdyenPPImplementationTrainingTestECOM
ADYEN_HMAC_KEY=8A3A50AC2DDBE25E6D4090393E58E2B67E97068A204A09FBD98D49D6FA570CC3
