spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent_output = true

# This configures Spring Boot to trust and use forwarded headers (like X-Forwarded-For) when behind a proxy or load balancer
server.forward-headers-strategy=framework 

server.port=8080
ADYEN_API_KEY=AQFDhmfxJ4/LbhBHw0m/n3Q5qf3VaY9UCJ16aExb1nSuk2NFisZiGclvMiVgB/7xzYuhmDgJH1GsgudQETXfW49Jvf/ZHBDBXVsNvuR83LVYjEgiTGAH-MkyUCstEz1Kz5r/db/LE9Ya+EcYpXD/dPS6HcUb5YD8=-i1iBPFEyr_sx$v9(%,A
ADYEN_CLIENT_KEY=test_HNY6C6IYO5EIBOPFRUYJFORINYZZM656
ADYEN_MERCHANT_ACCOUNT=AdyenPPImplementationTrainingTestECOM
ADYEN_HMAC_KEY=B361CB6CEB095A9AEBC8A44B3542DF76B990C06591A51CF2739129828B607E1F
